spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/talentboard_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false
    encoding: UTF-8
server:
  port: 8080
